services:
  - type: web
    name: boardingnest
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn boardingnest.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.8
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: boardingnest-db
          property: connectionString

databases:
  - name: boardingnest-db
    databaseName: boardingnest
    user: boardingnest
